name: Kwiki-Icons-Crystal
version: 0.10
abstract: Kwiki Crystal Icons Plugin
author: Matt Howard <mhoward@cpan.org>
license: gpl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.30
  Kwiki::Icons: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
